[project]
name = "elvanto"
version = "1.0.0"
description = "Add a short description here"
authors = ["Sejin Kim <hello@sejin.kim>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64"]

[tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."

[dependencies]
python = "3.10.*"
google-api-core = ">=2.19.0,<2.20"
thefuzz = ">=0.22.1,<0.23"
pandas = ">=2.2.2,<2.3"
gspread = ">=5.12.4,<5.13"
python-dotenv = ">=1.0.1,<1.1"
pip = ">=24.0,<25"
tqdm = ">=4.66.4,<4.67"
joblib = ">=1.4.2,<1.5"
