[project]
name = "elvanto"
version = "1.0.0"
description = "Add a short description here"
authors = ["Sejin Kim <hello@sejin.kim>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64", "linux-aarch64"]

[tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."
services    = "python scripts/get_services.py"
people      = "python scripts/get_people.py"
pull        = { depends-on = ["people", "services"] }
flows       = { cmd = ["python", "scripts/get_people_flows.py"], 
                depends-on = ["people"] }
teams       = { cmd = ["python", "scripts/get_team_stats.py"], 
                depends-on = ["pull"] } 

[dependencies]
python = "3.10.*"
google-api-core = ">=2.19.0,<2.20"
thefuzz = ">=0.22.1,<0.23"
pandas = ">=2.2.2,<2.3"
gspread = ">=5.12.4,<5.13"
python-dotenv = ">=1.0.1,<1.1"
pip = ">=24.0,<25"
tqdm = ">=4.66.4,<4.67"
joblib = ">=1.4.2,<1.5"
openpyxl = ">=3.1.4,<3.2"
notebook = ">=7.2.1,<7.3"
